name: line_secrets
on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:
env:
   LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
   GROUP_ID: ${{ secrets.GROUP_ID }}
   TO: ${{ secrets.TO }}
jobs:
  numpy-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'x64'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Python
      run: python garbage_message.py

